### DISCUSSION TITLE
Next steps with this project

### DISCUSSION THREAD

**Discussion by WieFel** [TinyCommunity/tinycolor2#2] [General]
So I would suggest that we take the following next steps:

1. Edit the readme: creadit the previous authors of tinycolor package and adapt other stuff where needed
2. Set up organization on pub.dev and publish first version of tinycolor2 there
3. Get PRs with null safety and others over here, check and merge them

**Comment by TNorbury** [comment]
We should also take a look at the issues in the original repo and decide which ones will need to be migrated over

**Reply by calvintam236** [reply]
Done. I have left comment in those issues that require to be migrated over.

**Comment by calvintam236** [comment]
> 1. Edit the readme: creadit the previous authors of tinycolor package and adapt other stuff where needed

I think when they make a PR, they can add their name into README. We should make a CONTRIBUTING.

> 2. Set up organization on pub.dev and publish first version of tinycolor2 there

We can do this after updating the readme.

> 3. Get PRs with null safety and others over here, check and merge them

I have commented in the original PRs and let’s see if they are making a PR on this side soon.

**Reply by calvintam236** [reply]
I just added issue templates.

**Reply by calvintam236** [reply]
Created automated projects for feature requests and bug triage: https://github.com/TinyCommunity/tinycolor2/projects

**Reply by calvintam236** [reply]
Updated `pubspec` for the new repo name, new version and git repo url

**Reply by calvintam236** [reply]
Branch protection added. Dependabot alert has enabled.

**Comment by WieFel** [comment]
LGTM.

> I think when they make a PR, they can add their name into README. We should make a CONTRIBUTING.
> 

You mean a section "Contributing"?

**Reply by calvintam236** [reply]
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by calvintam236** [comment]
@WieFel Should we add CI build testing?

**Reply by WieFel** [reply]
Yes why not! I am actually not that experienced with testing yet. So I'd love to learn more about it.

Maybe we can also add https://flutter.dev/docs/release/breaking-changes/flutter-lints-package and check if there's a github action for it as well.

**Reply by calvintam236** [reply]
I am thinking to use Github Action with Docker (I have a Flutter project built with Bitbucket pipelines. It should be similar to use in GH action.)

```yaml
image: cirrusci/flutter:2.0.6

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - flutter
          script:
            - flutter doctor -v
            - flutter pub get
            - flutter analyze
            - flutter format --set-exit-if-changed --dry-run .
            - flutter test
  branches:
    main:
      - step:
          caches:
            - flutter
          script:
            - flutter doctor -v
            - flutter pub get
            - flutter analyze
            - flutter format --set-exit-if-changed --dry-run .
            - flutter test
    dev:
      - step:
          caches:
            - flutter
          script:
            - flutter doctor -v
            - flutter pub get
            - flutter analyze
            - flutter format --set-exit-if-changed --dry-run .
            - flutter test

definitions:
  caches:
    flutter: $FLUTTER_ROOT
```
